CFLAGS= -Wall -fpic -coverage -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)
#To run playdom you need to entere: ./playdom <any integer number> like ./playdom 10*/
testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc  -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

badTestDrawCard: badTestDrawCard.c dominion.o rngs.o
	gcc -o badTestDrawCard -g  badTestDrawCard.c dominion.o rngs.o $(CFLAGS)

testBuyCard: testDrawCard.c dominion.o rngs.o
	gcc -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

testAll: dominion.o testSuite.c
	gcc -o testSuite testSuite.c -g  dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

runtests: testDrawCard 
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out


player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

unittestresults: myAssert.h myAssert.c unittest1.c dominion.o rngs.o
	gcc -o unittest1 unittest1.c myAssert.c -g dominion.o rngs.o $(CFLAGS)
	@echo UNIT TEST 1 > unittestresults.out
	./unittest1 >> unittestresults.out
	gcc -o unittest2 unittest2.c myAssert.c -g dominion.o rngs.o $(CFLAGS)
	@echo UNIT TEST 2 >> unittestresults.out
	./unittest2 >> unittestresults.out
	gcc -o unittest3 unittest3.c myAssert.c -g dominion.o rngs.o $(CFLAGS)
	@echo UNIT TEST 3 >> unittestresults.out
	./unittest3 >> unittestresults.out
	gcc -o unittest4 unittest4.c myAssert.c -g dominion.o rngs.o $(CFLAGS)
	@echo UNIT TEST 4 >> unittestresults.out
	./unittest4 >> unittestresults.out
	gcc -o cardtest1 cardtest1.c myAssert.c -g dominion.o rngs.o $(CFLAGS)
	@echo CARD TEST 1 >> unittestresults.out
	./cardtest1 >> unittestresults.out
	gcc -o cardtest2 cardtest2.c myAssert.c -g dominion.o rngs.o $(CFLAGS)
	@echo CARD TEST 2 >> unittestresults.out
	./cardtest2 >> unittestresults.out
	gcc -o cardtest3 cardtest3.c myAssert.c -g dominion.o rngs.o $(CFLAGS)
	@echo CARD TEST 3 >> unittestresults.out
	./cardtest3 >> unittestresults.out
	gcc -o cardtest4 cardtest4.c myAssert.c -g dominion.o rngs.o $(CFLAGS)
	@echo CARD TEST 4 >> unittestresults.out
	./cardtest4 >> unittestresults.out
	gcov -b dominion.c >> unittestresults.out
	cat dominion.c.gcov >> unittestresults.out

all: playdom player 

clean:
	rm -f *.o playdom.exe playdom player player.exe  *.gcov *.gcda *.gcno *.so *.out testDrawCard testDrawCard.exe
